HavaDurumuApi2/Models/Data.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HavaDurumuApi2.Models
{
    public class Data
    {
        public int ID { get; set; }
        public string Sehir { get; set; }
        public float Derece { get; set; }
    }
}

HavaDurumuApi2/Models/ErrorViewModel.cs
using System;

namespace HavaDurumu.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HavaDurumuApi2/Models/ListData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HavaDurumuApi2.Models;

namespace HavaDurumuApi2
{
    public static class ListData 
    {
        static List<Data> dataList = new List<Data>();

        public static List<Data> getHavaDurumu()
        {
            return dataList;
        }
        public static void addHavaDurumu(Data data)
        {
            dataList.Add(data);
        }
    }
}

HavaDurumuApi2/Controllers/AddController.cs
using HavaDurumu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using HavaDurumuApi2;
using HavaDurumuApi2.Models;
using Microsoft.AspNetCore.Http;

namespace HavaDurumuApi2.Controllers
{
    public class AddController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Data data)
        {
            HavaDurumuApi2.ListData.addHavaDurumu(data);
            return (RedirectToAction("Index","Home"));
        }
    }
}

HavaDurumuApi2/Controllers/HomeController.cs
using HavaDurumu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using HavaDurumuApi2;
using HavaDurumuApi2.Models;
using Microsoft.AspNetCore.Http;

namespace HavaDurumu.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        List<Data> HavaDurumlari;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            HavaDurumlari =  ListData.getHavaDurumu();
            ViewBag.HDL = HavaDurumlari;
            return View(HavaDurumlari);
        }
        [HttpPost]
        public IActionResult Index(string search)
        {
           
            search = Request.Form["Hava Durumu"].ToString();
            HavaDurumlari = ListData.getHavaDurumu().Where(m => m.Sehir == search).ToList();
           
            return View(HavaDurumlari);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HavaDurumuApi2/Views/Add/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<form class="form-group" method="post">
    <div>
        <label>ID</label>
        <input type="text" class="form-control" name="ID"
    </div>
    <div>
        <label>Sehir</label>
        <input type="text" class="form-control" name="Sehir"
    </div>
    <div>
        <label>Derece</label>
        <input type="text" class="form-control" name="Derece"
    </div>
    <div>
        <button class="btn btn-info">Hava Durumu Ekle</button>
    </div>
</form>

HavaDurumuApi2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
        @using (Html.BeginForm("Index", "Home", FormMethod.Post))
        {
        <div>
            @Html.DropDownList("Hava Durumu", new SelectList(Model, "Sehir", "Sehir"), "Şehir Seçin", new { @Sehir = "Sehir" })
        </div>
        <div>
            <input type="submit" value="Filtrele" />
        </div>
        
        }
        <input type="button" value="Filtreleri Kaldır" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" />
        @model IEnumerable<HavaDurumuApi2.Models.Data>
        <table class="table">
            <tr>
                <td>ID</td>
                <td>Şehir</td>
                <td>Derece</td>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayTextFor(m => item.ID)</td>
                    <td>@Html.DisplayTextFor(m => item.Sehir)</td>
                    <td>@Html.DisplayTextFor(m => item.Derece)</td>
                </tr>
            }
        </table>
        <input type="button" value="Hava Durumu Ekle" onclick="@("window.location.href='" + @Url.Action("Index", "Add") + "'");" />
    }
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
            <input type="text" class="form-control" name="ID", id="ID" />
            <input type="submit" value="Arama yap" />
    }


 </div>

HavaDurumuApi2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HavaDurumu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HavaDurumu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HavaDurumu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>